name: GEM Data Scraper
on:
  workflow_dispatch:  # Manual trigger
  schedule:
    - cron: '0 2 * * *'  # Daily at 2 AM UTC

jobs:
  scrape:
    runs-on: ubuntu-latest
    timeout-minutes: 360  # 6 hour max
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm install
        
      - name: Run scraper
        run: node your-script.js
        
      - name: Upload scraped data
        uses: actions/upload-artifact@v4
        if: always()  # Upload even if script fails partially
        with:
          name: gem-scraped-data
          path: ./all_docs.json
          retention-days: 30
